#!/bin/bash

# send from non-bond NIC to bond NIC

CLIENT_PORT="-k 10000"
CLIENT_IP="-j 192.168.0.2"
CLIENT_MAC="-B 08:c0:eb:d4:ec:07"
CLIENT_IB_DEV="-d mlx5_1"

SERVER_PORT="-K 10013"
SERVER_IP="-J 10.68.147.1"
SERVER_MAC="-E 08:c0:eb:d4:ec:06"
SERVER_IB_DEV="-d mlx5_0"

LISTEN_PORT="-p 20000"

ITERATIONS="-n 1000000"

SERVER_CPU=3
CLIENT_CPU=5

SERVER_ARGS="--use_hugepages ${SERVER_IB_DEV} ${SERVER_MAC} ${SERVER_IP} ${SERVER_PORT} ${CLIENT_MAC} ${CLIENT_IP} ${CLIENT_PORT} ${LISTEN_PORT} ${ITERATIONS} --server"
CLIENT_ARGS="--use_hugepages ${CLIENT_IB_DEV} ${SERVER_MAC} ${SERVER_IP} ${SERVER_PORT} ${CLIENT_MAC} ${CLIENT_IP} ${CLIENT_PORT} ${LISTEN_PORT} ${ITERATIONS} --client"

TASK="./raw_ethernet_bw"

if [[ "$1" == "server" ]]
then
  taskset -c ${SERVER_CPU} ${TASK} ${SERVER_ARGS}
elif [[ "$1" == "client" ]]
then
  taskset -c ${CLIENT_CPU} ${TASK} ${CLIENT_ARGS}
else
  echo "usage: ./run <client|server>"
  exit 2
fi

exit $?
